services:
  knishbot:
    build: .
    container_name: knishbot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DEFAULT_MC_SERVER${DEFAULT_MC_SERVER}
    volumes:
      - /home/administrator/docker/knishbot:/app/data #Set this to where your JSON file is for Minecraft server logging
